// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository.go -package=mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/k-akari/payment.com/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockcompanyRepository is a mock of companyRepository interface.
type MockcompanyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcompanyRepositoryMockRecorder
}

// MockcompanyRepositoryMockRecorder is the mock recorder for MockcompanyRepository.
type MockcompanyRepositoryMockRecorder struct {
	mock *MockcompanyRepository
}

// NewMockcompanyRepository creates a new mock instance.
func NewMockcompanyRepository(ctrl *gomock.Controller) *MockcompanyRepository {
	mock := &MockcompanyRepository{ctrl: ctrl}
	mock.recorder = &MockcompanyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompanyRepository) EXPECT() *MockcompanyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcompanyRepository) Create(ctx context.Context, company *domain.Company) (domain.CompanyID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, company)
	ret0, _ := ret[0].(domain.CompanyID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockcompanyRepositoryMockRecorder) Create(ctx, company any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcompanyRepository)(nil).Create), ctx, company)
}

// GetByID mocks base method.
func (m *MockcompanyRepository) GetByID(ctx context.Context, companyID domain.CompanyID) (*domain.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, companyID)
	ret0, _ := ret[0].(*domain.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockcompanyRepositoryMockRecorder) GetByID(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockcompanyRepository)(nil).GetByID), ctx, companyID)
}

// MockclientRepository is a mock of clientRepository interface.
type MockclientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockclientRepositoryMockRecorder
}

// MockclientRepositoryMockRecorder is the mock recorder for MockclientRepository.
type MockclientRepositoryMockRecorder struct {
	mock *MockclientRepository
}

// NewMockclientRepository creates a new mock instance.
func NewMockclientRepository(ctrl *gomock.Controller) *MockclientRepository {
	mock := &MockclientRepository{ctrl: ctrl}
	mock.recorder = &MockclientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockclientRepository) EXPECT() *MockclientRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockclientRepository) Create(ctx context.Context, client *domain.Client) (domain.ClientID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, client)
	ret0, _ := ret[0].(domain.ClientID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockclientRepositoryMockRecorder) Create(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockclientRepository)(nil).Create), ctx, client)
}

// GetByID mocks base method.
func (m *MockclientRepository) GetByID(ctx context.Context, clientID domain.ClientID) (*domain.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, clientID)
	ret0, _ := ret[0].(*domain.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockclientRepositoryMockRecorder) GetByID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockclientRepository)(nil).GetByID), ctx, clientID)
}

// MockinvoiceRepository is a mock of invoiceRepository interface.
type MockinvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockinvoiceRepositoryMockRecorder
}

// MockinvoiceRepositoryMockRecorder is the mock recorder for MockinvoiceRepository.
type MockinvoiceRepositoryMockRecorder struct {
	mock *MockinvoiceRepository
}

// NewMockinvoiceRepository creates a new mock instance.
func NewMockinvoiceRepository(ctrl *gomock.Controller) *MockinvoiceRepository {
	mock := &MockinvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockinvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinvoiceRepository) EXPECT() *MockinvoiceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockinvoiceRepository) Create(ctx context.Context, invoice *domain.Invoice) (domain.InvoiceID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invoice)
	ret0, _ := ret[0].(domain.InvoiceID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockinvoiceRepositoryMockRecorder) Create(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockinvoiceRepository)(nil).Create), ctx, invoice)
}

// ListByPaymentDueDateBetween mocks base method.
func (m *MockinvoiceRepository) ListByPaymentDueDateBetween(ctx context.Context, coid domain.CompanyID, from, to *time.Time) ([]*domain.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPaymentDueDateBetween", ctx, coid, from, to)
	ret0, _ := ret[0].([]*domain.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPaymentDueDateBetween indicates an expected call of ListByPaymentDueDateBetween.
func (mr *MockinvoiceRepositoryMockRecorder) ListByPaymentDueDateBetween(ctx, coid, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPaymentDueDateBetween", reflect.TypeOf((*MockinvoiceRepository)(nil).ListByPaymentDueDateBetween), ctx, coid, from, to)
}
